DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(128),
  cover_image TEXT NOT NULL,
  rating TEXT NOT NULL,
  PRICE TEXT NOT NULL,
  is_in_stock BOOLEAN
)